### ISSUE TITLE
Dead link on README.md

### ISSUE THREAD

**Issue by jzhuge** [Azure/azure-data-lake-store-java#1]
The link to https://azure.github.io/azure-data-lake-store-java/ does not work.

**Comment by asikaria-msft** [comment]
Thanks for reporting! I will fix on the next push.

**Comment by asikaria-msft** [comment]
BTW, the correct link is https://azure.github.io/azure-data-lake-store-java/javadoc/

**Comment by jzhuge** [comment]
Thx, Atul.

**Comment by asikaria-msft** [comment]
Fixed now.
