### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by malkochoglu** [Azure/azure-data-lake-store-java#10]
Hi,
I don't see any proxy support in your sdk. Can you please confirm ?  Many corps use proxy and without Proxy support how come on prem systems behind a proxy can work with Azure?
Thanks

**Comment by asikaria-msft** [comment]
Java supports specifying proxy on the command-line:
-DproxySet=true -DproxyHost=squirrel -DproxyPort=8888

**Comment by malkochoglu** [comment]
Never tried somehow this since we started with proxy authenticator requirement. Looks like this is working but answer needs an update. That is:
-Dhttps.proxyHost=XXXX -Dhttps.proxyPort=YYYY

Thanks.

**Comment by pegerto** [comment]
Hi @asikaria-msft 
I believe that the command options are not an option for some cases. In our case, we may have multiple data process running over the same JVM and we want to configure the proxy by connection.

In particular, when an ETL implement cross-application requirements we would like to configure multiple users per connection to the proxy.

Would you be kind to reopen the request?
