### ISSUE TITLE
Why RefreshToken does not use tenant id based auth endpoint

### ISSUE THREAD

**Issue by jzhuge** [Azure/azure-data-lake-store-java#4]
https://github.com/Azure/azure-data-lake-store-java/blob/master/src/main/java/com/microsoft/azure/datalake/store/oauth2/AzureADAuthenticator.java#L75

Why RefreshToken does not use tenant id based auth endpoint like ClientCreds does?

**Comment by asikaria-msft** [comment]
The way I understand it, for Client Creds just the client ID and secret is not sufficient - AAD also needs to know which directory instance to authenticate against. However for Refresh token, a user authenticates with something of the type userid@domain, which gives AAD enough information to know which directory instance to use. So in the case of refresh token, the auth URL can be a "common" url, and the auth process can figure out the directory instance to go to.

If you look at different auth endpoints for Client Creds, you will notice that the only thing different between the URLs is the tenant ID guid embedded in the url - this is the pointer to the directory instance.

**Comment by jzhuge** [comment]
Thanks Atul.
