### ISSUE TITLE
WildFly upgrade - security issues

### ISSUE THREAD

**Issue by alex-infa** [Azure/azure-data-lake-store-java#47]
WildFly 17.0.1 currently used by azure-data-lake-store-sdk is outdated and identified as containing multiple security vulnerabilities:

![image](https://user-images.githubusercontent.com/76075326/102280953-1a336f00-3f3f-11eb-8fa6-9f954d32cc42.png)

Please upgrade to the latest version (currently 21.0.1) to mitigate those.

Thanks

**Comment by rahuldutta90** [comment]
@alex-infa  which wildfly package you are talking about? We have this one:
<groupId>org.wildfly.openssl</groupId>
      <artifactId>wildfly-openssl</artifactId>
      <version>1.0.7.Final</version>

Not sure which version you are reffering by 17.0.1? 

Here are the versions: https://mvnrepository.com/artifact/org.wildfly.openssl/wildfly-openssl

**Comment by alex-infa** [comment]
I reviewed our scan results once again, and it looks like the tool got confused between WildFly application server, which the above issues are for, and wildfly-openssl package actually use by the sdk. I do not see any issues reported for wildfly-openssl.

Thank you for the response Rahul, I'm closing this.
